<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>

<table>
  <tr>
    <th class="post-id">Id</th>
    <th class="post-name">Comment</th>
    <th>Content</th>
  </tr>
    <?php
        foreach ($block->getCommentsCollection($product_id) as $key=>$comment){
            echo '<tr>
                    <td>'.$comment->getCommentId().'</td>
                    <td>'.$comment->getComment().'</td>
                    <td>'.$comment->getCreatedAt().'</td>
                  </tr>';
        }
    ?>
</table>

</body>
</html>